// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for VpcCidrBlockResolverFunction
 */
export interface VpcCidrBlockResolverFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/ec2/lib/custom-resources/vpc-cidr-block-resolver.
 */
export class VpcCidrBlockResolverFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: VpcCidrBlockResolverFunctionProps) {
    super(scope, id, {
      description: 'src/ec2/lib/custom-resources/vpc-cidr-block-resolver.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/ec2/lib/custom-resources/vpc-cidr-block-resolver.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}