import { ArnFormat, IResolvable, IResource, Resource, ResourceProps, Token } from 'aws-cdk-lib';
import { CfnIPAMScope } from 'aws-cdk-lib/aws-ec2';
import { IConstruct } from 'constructs';
import { IIpam } from './ipam';
import { IIpamPool, IpamPool, IpamPoolOptions } from './ipam-pool';
import { DynamicReference } from '../core/dynamic-reference';
import { ResourceImporter } from '../utils/importer';


/**
 * Represents an IPAM scope in AWS.
 */
export interface IIpamScope extends IResource {
  /**
   * The ARN of the scope.
   */
  readonly ipamScopeArn: string;

  /**
   * The ID of an IPAM scope.
   */
  readonly ipamScopeId: string;

  /**
   * The ARN of an IPAM.
   */
  readonly ipamScopeIpamArn: string;

  /**
   * Defines if the scope is the default scope or not.
   */
  readonly ipamScopeIsDefault: IResolvable;

  /**
   * The number of pools in a scope.
   */
  readonly ipamScopePoolCount: number;

  /**
   * The type of the scope.
   */
  readonly ipamScopeType: string;

  /**
   * Adds an IPAM pool to the IPAM scope.
   *
   * A pool is a collection of contiguous IP address ranges (or CIDRs). IPAM
   * pools enable you to organize your IP addresses according to your routing
   * and security needs.
   *
   * @see [How IPAM works](https://docs.aws.amazon.com/vpc/latest/ipam/how-it-works-ipam.html)
   *
   * @param id A name to be associated with the pool bing added. A unique id
   * must be used each time the method is invoked.
   * @param options Arguments specifying the details of the pool being added.
   * @returns The pool that was added to the scope.
   */
  addPool(id: string, options?: IpamPoolOptions): IIpamPool;
}

/**
 * A base class providing common functionality between created and imported
 * IPAM scopes.
 */
abstract class IpamScopeBase extends Resource implements IIpamScope {
  /**
   * The ARN of the scope.
   */
  public abstract readonly ipamScopeArn: string;

  /**
   * The ID of an IPAM scope.
   */
  public abstract readonly ipamScopeId: string;

  /**
   * The ARN of an IPAM.
   */
  public abstract readonly ipamScopeIpamArn: string;

  /**
   * Defines if the scope is the default scope or not.
   */
  public abstract readonly ipamScopeIsDefault: IResolvable;

  /**
   * The number of pools in a scope.
   */
  public abstract readonly ipamScopePoolCount: number;

  /**
   * The type of the scope.
   */
  public abstract readonly ipamScopeType: string;

  /**
   * Adds an IPAM pool to the IPAM scope.
   *
   * A pool is a collection of contiguous IP address ranges (or CIDRs). IPAM
   * pools enable you to organize your IP addresses according to your routing
   * and security needs.
   *
   * @see [How IPAM works](https://docs.aws.amazon.com/vpc/latest/ipam/how-it-works-ipam.html)
   *
   * @param id A name to be associated with the pool bing added. A unique id
   * must be used each time the method is invoked.
   * @param options Arguments specifying the details of the pool being added.
   * @returns The pool that was added to the scope.
   */
  public addPool(id: string, options: IpamPoolOptions = {}): IIpamPool {
    return new IpamPool(this, `pool-${id}`, {
      ...options,
      ipamScope: this,
    });
  }
}

/**
 * Configuration for importing an existing IPAM scope.
 */
export interface IpamScopeAttributes {
  /**
   * The IPAM to which the scope belongs.
   */
  readonly ipam?: IIpam;

  /**
   * The Amazon Resource Name (ARN) of the IPAM scope.
   */
  readonly ipamScopeArn?: string;

  /**
   * The ID generated by AWS for the IPAM scope.
   */
  readonly ipamScopeId?: string;

  /**
   * Defines if the scope is the default scope or not.
   */
  readonly isDefault?: boolean;

  /**
   * The number of pools in a scope.
   */
  readonly poolCount?: number;

  /**
   * The type of the scope.
   */
  readonly scopeType?: string;
}

/**
 * Optional configuration for the IPAM scope resource.
 */
export interface IpamScopeOptions {
  /**
   * The description of the scope.
   *
   * @see [IPAMScope Description](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html#cfn-ec2-ipamscope-description)
   */
  readonly description?: string;
}

/**
 * Configuration for the IPAM scope resource.
 */
export interface IpamScopeProps extends ResourceProps, IpamScopeOptions {
  /**
   * The IPAM for which you're creating this scope.
   *
   * @see [IPAMScope IpamId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html#cfn-ec2-ipamscope-ipamid)
   */
  readonly ipam: IIpam;
}

/**
 * Represents an IPAM scope.
 *
 * In IPAM, a scope is the highest-level container within IPAM. An IPAM
 * contains two default scopes. Each scope represents the IP space for a single
 * network. The private scope is intended for all private IP address space. The
 * public scope is intended for all public IP address space. Scopes enable you
 * to reuse IP addresses across multiple unconnected networks without causing
 * IP address overlap or conflict.
 *
 * @see [AWS::EC2::IPAMScope](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html)
 */
export class IpamScope extends IpamScopeBase {
  /**
   * The format for Amazon Resource Names (ARN's) for IPAM scope resources.
   */
  public static readonly ARN_FORMAT: ArnFormat = ArnFormat.SLASH_RESOURCE_NAME;

  /**
   * Imports an existing IPAM scope by specifying its Amazon Resource Name
   * (ARN).
   *
   * @param scope A CDK Construct that will serve as this resources's parent in
   * the construct tree.
   * @param id A name to be associated with the stack and used in resource
   * naming. Must be unique within the context of 'scope'.
   * @param ipamScopeArn The ARN of the existing IPAM scope to be imported.
   * @returns An object representing the imported IPAM scope.
   */
  public static fromIpamScopeArn(scope: IConstruct, id: string, ipamScopeArn: string): IIpamScope {
    return IpamScope.fromIpamScopeAttributes(scope, id, {
      ipamScopeArn: ipamScopeArn,
    });
  }

  /**
   * Imports an existing IAPM scope by explicitly specifying its attributes.
   *
   * @param scope A CDK Construct that will serve as this resources's parent in
   * the construct tree.
   * @param id A name to be associated with the stack and used in resource
   * naming. Must be unique within the context of 'scope'.
   * @param attrs The attributes of the existing IPAM scope to be imported.
   * @returns An object representing the imported IPAM scope.
   */
  public static fromIpamScopeAttributes(scope: IConstruct, id: string, attrs: IpamScopeAttributes): IIpamScope {
    const importer = new ResourceImporter(scope, id, {
      arnFormat: IpamScope.ARN_FORMAT,
      service: 'ec2',
      resource: 'ipam-scope',
    });

    const identities = importer.resolveIdentities(attrs.ipamScopeArn, attrs.ipamScopeId);
    const props = importer.resolveProperties({
      ipamScopeIpamArn: attrs.ipam?.ipamArn,
      ipamScopeIsDefault: attrs.isDefault,
      ipamScopePoolCount: attrs.poolCount,
      ipamScopeType: attrs.scopeType,
    });

    class Import extends IpamScopeBase {
      public readonly ipamScopeArn: string = identities.arn;
      public readonly ipamScopeId: string = identities.id;
      public readonly ipamScopeIpamArn: string = Token.asString(props.ipamScopeIpamArn);
      public readonly ipamScopeIsDefault: IResolvable = Token.asAny(props.ipamScopeIsDefault);
      public readonly ipamScopePoolCount: number = Token.asNumber(props.ipamScopePoolCount);
      public readonly ipamScopeType: string = Token.asString(props.ipamScopeType);
    }

    return new Import(scope, id);
  }

  /**
   * Imports an existing IPAM scope by explicitly specifying its AWS generated
   * ID.
   *
   * @param scope A CDK Construct that will serve as this resources's parent in
   * the construct tree.
   * @param id A name to be associated with the stack and used in resource
   * naming. Must be unique within the context of 'scope'.
   * @param ipamScopeId The AWS generated ID of the existing IPAM scope to be
   * imported.
   * @returns An object representing the imported IPAM scope.
   */
  public static fromIpamScopeId(scope: IConstruct, id: string, ipamScopeId: string): IIpamScope {
    return IpamScope.fromIpamScopeAttributes(scope, id, {
      ipamScopeId: ipamScopeId,
    });
  }

  /**
   * The description of the scope.
   *
   * @see [IPAMScope Description](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html#cfn-ec2-ipamscope-description)
   *
   * @group Inputs
   */
  public readonly description?: string;

  /**
   * The IPAM for which you're creating this scope.
   *
   * @see [IPAMScope IpamId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html#cfn-ec2-ipamscope-ipamid)
   *
   * @group Inputs
   */
  public readonly ipam: IIpam;

  /**
   * The underlying IPAM scope CloudFormation resource.
   *
   * @see [AWS::EC2::IPAMScope](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-ipamscope.html)
   *
   * @group Resources
   */
  public readonly resource: CfnIPAMScope;

  /**
   * The ARN of the scope.
   */
  public readonly ipamScopeArn: string;

  /**
   * The ID of an IPAM scope.
   */
  public readonly ipamScopeId: string;

  /**
   * The ARN of an IPAM.
   */
  public readonly ipamScopeIpamArn: string;

  /**
   * Defines if the scope is the default scope or not.
   */
  public readonly ipamScopeIsDefault: IResolvable;

  /**
   * The number of pools in a scope.
   */
  public readonly ipamScopePoolCount: number;

  /**
   * The type of the scope.
   */
  public readonly ipamScopeType: string;


  /**
   * Creates a new instance of the IpamScope class.
   *
   * @param scope A CDK Construct that will serve as this resource's parent in
   * the construct tree.
   * @param id A name to be associated with the stack and used in resource
   * naming. Must be unique within the context of 'scope'.
   * @param props Arguments related to the configuration of the resource.
   */
  public constructor(scope: IConstruct, id: string, props: IpamScopeProps) {
    super(scope, id, props);

    this.description = props.description;
    this.ipam = props.ipam;

    this.resource = new CfnIPAMScope(this, 'Resource', {
      description: this.description,
      ipamId: this.ipam.ipamId,
    });

    this.ipamScopeArn = DynamicReference.string(this, this.resource.attrArn);
    this.ipamScopeId = DynamicReference.string(this, this.resource.ref);
    this.ipamScopeIpamArn = DynamicReference.string(this, this.resource.attrIpamArn);
    this.ipamScopeIsDefault = DynamicReference.any(this, this.resource.attrIsDefault);
    this.ipamScopePoolCount = DynamicReference.number(this, this.resource.attrPoolCount);
    this.ipamScopeType = DynamicReference.string(this, this.resource.attrIpamScopeType);
  }
}